Add Icinga DB support
Icinga/icingaweb2-module-nagvis pull request #48
Opened 2022-07-01 15:17 UTC by yhabteab

2022-07-13 14:54 UTC, yhabteab commented
refs https://github.com/Icinga/icingadb-web/pull/594

2022-07-14 11:06 UTC, yhabteab commented
Here is a vm for testing it: http://10.27.0.47/icingaweb2

2022-08-04 07:52 UTC, lippserd requested changes
The `GlobalBackendido` class is not necessary.

2022-08-04 07:52 UTC, lippserd commented on doc/02-Installation.md
> +backend = "ido"
I would not change this backend because the IDO/NDO backend is already included in NagVis.

2022-08-04 07:52 UTC, lippserd commented on doc/02-Installation.md
> +Additionally, to make sure that the backend types provided by this module are being detected by `Nagvis`, you either
Specify only the Icinga DB backend here.

2022-08-04 07:52 UTC, lippserd commented on library/nagvis-includes/GlobalBackendicingadb.php
> +class GlobalBackendicingadb implements GlobalBackendInterface
Please use a const for the `~~` separator, e.g. `HOST_SERVICE_SEPARATOR`.

2022-08-04 07:52 UTC, lippserd commented on library/nagvis-includes/GlobalBackendicingadb.php
> +        if ($name1Pattern !== '') {
This should refer to `name2`.

2022-11-23 06:17 UTC, mwaldmueller commented
The first test on my small demo environment was successful. Hopefully I get the chance to test it at customers site within the next weeks.

2022-11-24 23:00 UTC, miken32 commented
Documentation for the monitoring module says "Note for Icinga DB Users: This module is only for the IDO backend. Use [Icinga DB Web](https://github.com/Icinga/icingadb-web) instead." Does it make sense that the monitoring module is a requirement for the icingadb module?

I'm trying to get this patch up and running to test with, but I find myself installing more and more IDO stuff that icingadb was supposed to replace.

2022-11-25 08:22 UTC, yhabteab commented
> Documentation for the monitoring module says "Note for Icinga DB Users: This module is only for the IDO backend. Use [Icinga DB Web](https://github.com/Icinga/icingadb-web) instead." Does it make sense that the monitoring module is a requirement for the nagvis module?

I don't really get what you mean by that, but the monitoring module can still be installed and used. It is also absolutely valid that it is required for the Nagvis module, though it's not a mandatory, as you can see here.

<img width="618" alt="Bildschirm­foto 2022-11-25 um 09 09 19" src="https://user-images.githubusercontent.com/57616252/203931943-c1389d7e-5ee6-4859-a9ff-2288f193a4ff.png">

> I'm trying to get this patch up and running to test with, but I find myself installing more and more IDO stuff that icingadb was supposed to replace.

When you want to test this patch, you just need to install [Icinga DB Web](https://github.com/Icinga/icingadb-web) as described in the documentation and follow the configuration steps given [here](https://github.com/Icinga/icingaweb2-module-nagvis/blob/add-icingadb-support/doc/02-Installation.md#nagvis-configuration).

2022-11-25 08:24 UTC, lippserd commented
Is this documentation quote maybe from another module?

2022-11-25 17:32 UTC, miken32 commented
Thanks @yhabteab my patch to `module.info` didn't apply for whatever reason and I failed to notice. Once that was in place it worked as expected. I can confirm that our (very basic) nagvis map is now reading host state data from icingadb successfully.

2022-11-25 23:39 UTC, miken32 commented
Automaps from a hostgroup are not working:
>The requested feature getHostNamesInHostgroup is not provided by the backend (Backend-ID: icingadb_1, Backend-Type: icingadb). The requested view may not be available using this backend.

2022-11-28 11:49 UTC, yhabteab commented
> Edit: nvm I see no automaps are properly working, since icingadb decided not to include the ability to detect parent/child relationships. But for what it's worth:

I know Icinga DB doesn't support dependencies right now, but `getHostNamesInHostgroup()` can be implemented as you suggested above and don't have to wait for this feature of Icinga DB. Thanks for testing @miken32

2022-11-30 12:11 UTC, yhabteab commented
> Another minor bug; when adding a service to a map, the service dropdown doesn't populate after selecting a host. If the service is added manually via text file, the web UI shows an error when editing: "Current value is not a known option - falling back to input field"

Thank you very much for your feedback and testing. The services should now be correctly populated with the latest commit!

2023-01-20 07:04 UTC, mwaldmueller commented
Tested with commit 17889bbdefbf94fd015c0501406fc1c66d016d05

A few things I noticed:

1) Services should be round:

IDO:
![nagvis_service1_ido](https://user-images.githubusercontent.com/3973350/213635997-33e08195-f286-4359-8585-07f12fb4bf61.png)
Icinga DB:
![nagvis_service1_icingadb](https://user-images.githubusercontent.com/3973350/213636039-610ff29f-b974-4ded-9439-0ef411a80966.png)

2) The state of hostgroups is wrong:

IDO:
![nagvis_hostgroup1_ido](https://user-images.githubusercontent.com/3973350/213636418-1e133f93-9187-4f78-be42-ce3376614754.png)
Icinga DB:
![nagvis_hostgroup1_icingadb](https://user-images.githubusercontent.com/3973350/213636457-b1a771e8-2418-4098-82e4-060853d67f2e.png)

3) Same for servicegroups:

IDO:
![nagvis_servicegroup1_ido](https://user-images.githubusercontent.com/3973350/213636499-348d5baf-214c-4252-8f2b-9bc980f12354.png)
Icinga DB:
![nagvis_servicegroup1_icingadb](https://user-images.githubusercontent.com/3973350/213636541-99f962cc-1d99-4c86-9e4b-897b9314ae93.png)

2023-01-20 07:14 UTC, mwaldmueller commented
4) UNKNOWN in hostgroups:

IDO:
![nagvis_hostgroup2_ido](https://user-images.githubusercontent.com/3973350/213638224-7ecb23b9-637e-4839-8192-d26e205fb4d7.png)
Icinga DB:
![nagvis_hostgroup2_icingadb](https://user-images.githubusercontent.com/3973350/213638325-41dd6d65-a766-4e15-ac39-bb1f36b27101.png)

2023-01-20 11:11 UTC, yhabteab commented
<img width="622" alt="Bildschirm­foto 2023-01-20 um 11 56 27" src="https://user-images.githubusercontent.com/57616252/213681847-498126af-d3f1-4d2b-a56b-d3de411320f5.png">

<img width="622" alt="Bildschirm­foto 2023-01-20 um 11 55 42" src="https://user-images.githubusercontent.com/57616252/213681860-4b4f55c4-5484-40d7-8735-5723140078b4.png">

2023-01-20 15:56 UTC, yhabteab commented
<img width="795" alt="Bildschirm­foto 2023-01-20 um 16 56 30" src="https://user-images.githubusercontent.com/57616252/213744820-e6c9f116-254b-456a-8a56-4a24c9d68c7e.png">

2023-01-20 16:16 UTC, yhabteab commented
### Houtgroup in `OK` state
<img width="674" alt="Bildschirm­foto 2023-01-20 um 17 15 10" src="https://user-images.githubusercontent.com/57616252/213748864-c574a593-2521-4972-af65-d868483c99ea.png">

2023-01-23 13:06 UTC, yhabteab commented
I have now tested it quite extended with all possible configs and also with excludes, so far it works exactly like the `ndomy` backend.
<img width="1087" alt="Bildschirm­foto 2023-01-23 um 14 00 44" src="https://user-images.githubusercontent.com/57616252/214046042-b0dcbea8-65e4-40aa-a1b4-773744883206.png">

2023-01-31 07:31 UTC, lippserd approved these changes

2023-01-31 07:31 UTC, lippserd commented
@mwaldmueller Will you test the PR again?

2023-03-14 15:49 UTC, mwaldmueller commented
I had the chance to test again.

1) Acknowledgements in servicegroups

IDO:
![1_ido](https://user-images.githubusercontent.com/3973350/225056791-ce898021-616b-4ba0-a878-4862ec94c213.png)

Icinga DB:
![1_icingadb](https://user-images.githubusercontent.com/3973350/225056873-47c3f952-5e38-4116-a8cb-56dc7e8bc0c4.png)

2023-03-14 17:38 UTC, yhabteab commented
Thank you @mwaldmueller!
<img width="1076" alt="Bildschirm­foto 2023-03-14 um 18 36 07" src="https://user-images.githubusercontent.com/57616252/225091050-7dd80f3a-f229-4271-a787-2045a30887ab.png">

2023-03-14 18:14 UTC, miken32 commented on library/nagvis-includes/GlobalBackendicingadb.php
> +            $result[$item->host_name] = [
`$result` should be defined as an empty array at the beginning of this method

2023-03-14 21:43 UTC, miken32 commented
Other than my nitpick above (in case there is a JSON error you'll only get an undefined variable error, and not see the JSON error) I tested latest branch and it works great for us.

2023-03-15 09:27 UTC, yhabteab commented
> (in case there is a JSON error you'll only get an undefined variable error, and not see the JSON error)

Is the error triggered somewhere in this module? And does the error get displayed correctly with the `ndomy` backend?

2023-03-15 16:10 UTC, miken32 commented
> > (in case there is a JSON error you'll only get an undefined variable error, and not see the JSON error)
> 
> Is the error triggered somewhere in this module? And does the error get displayed correctly with the `ndomy` backend?

No it was a deprecation error in Nagvis (NagVis/nagvis#335) after updating to PHP 8.1. No idea if it works otherwise, we only have icingadb for storage, but it's Nagvis displaying the error so I imagine it's the same either way?

2023-03-15 16:47 UTC, yhabteab commented
> I imagine it's the same either way?

Yep, unfortunately! Nagvis doesn't support PHP 8.1 properly yet.

2023-03-16 12:23 UTC, mwaldmueller commented
After the last changes from @lippserd so that sticky acknowledgements are considered my tests were all successful. So, from my point of view: Ready to release! 🚀

2023-03-16 12:26 UTC, mwaldmueller approved these changes

2023-03-16 12:38 UTC, merged